server:
  port: 8081
spring:
  application:
    name: franchise-api
  data:
    mongodb:
      uri: mongodb://localhost:27017/franchise_db
  security:
    user:
      name: admin
      password: admin123