services:
  # Servicio 1: Base de Datos
  mongodb:
    image: mongo:7.0
    container_name: franchise-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:               
      - franchise-network  

  api:
    build: . 
    container_name: franchise-api
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/franchise_db 
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true 
    depends_on:
      mongodb:
        condition: service_healthy 
    networks:
      - franchise-network

volumes:
  mongo-data: 

networks:
  franchise-network: 
    driver: bridge